# Generated by Django 3.2.12 on 2022-04-05 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('Game_ID', models.AutoField(primary_key=True, serialize=False)),
                ('HomeAway', models.CharField(max_length=1)),
                ('Opponent', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Personnal',
            fields=[
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('F_Name', models.CharField(max_length=100)),
                ('L_Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('Shot_ID', models.AutoField(primary_key=True, serialize=False)),
                ('X_location', models.PositiveIntegerField()),
                ('Y_location', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('League', models.CharField(max_length=100)),
                ('Division', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wins', models.PositiveIntegerField()),
                ('Losses', models.PositiveIntegerField()),
                ('PIMS', models.PositiveIntegerField()),
                ('Shots', models.PositiveIntegerField()),
                ('Shots_against', models.PositiveIntegerField()),
                ('Team_ID', models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.personnal')),
                ('Shot_ID', models.ForeignKey(db_column='Shot_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.shot')),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.personnal')),
                ('Game_ID', models.ForeignKey(db_column='Game_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GamesPlayed', models.PositiveIntegerField()),
                ('Goals', models.PositiveIntegerField()),
                ('Assists', models.PositiveIntegerField()),
                ('Shots', models.PositiveIntegerField()),
                ('Hits', models.PositiveIntegerField()),
                ('F_wins', models.PositiveIntegerField()),
                ('F_losses', models.PositiveIntegerField()),
                ('Email', models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.personnal')),
                ('Team_ID', models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.PositiveIntegerField()),
                ('Weight', models.PositiveIntegerField()),
                ('Handedness', models.CharField(max_length=1)),
                ('Number', models.PositiveIntegerField()),
                ('Position', models.CharField(max_length=2)),
                ('Email', models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.personnal')),
                ('Team_ID', models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.team')),
            ],
        ),
        migrations.AddField(
            model_name='personnal',
            name='Team_ID',
            field=models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.team'),
        ),
        migrations.CreateModel(
            name='Game_Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_score', models.PositiveIntegerField()),
                ('Opponent_score', models.PositiveIntegerField()),
                ('Team_shots', models.PositiveIntegerField()),
                ('Opponent_shots', models.PositiveIntegerField()),
                ('Team_hits', models.PositiveIntegerField()),
                ('F_wins', models.PositiveIntegerField()),
                ('F_losses', models.PositiveIntegerField()),
                ('Game_ID', models.ForeignKey(db_column='Game_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.game')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_ID', models.ForeignKey(db_column='Game_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.game')),
                ('Shot_ID', models.ForeignKey(db_column='Shot_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.shot')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='Team_ID',
            field=models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.team'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.personnal')),
                ('Team_ID', models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.team')),
            ],
        ),
    ]
