# Generated by Django 3.2.12 on 2022-04-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('League', models.CharField(max_length=100)),
                ('Division', models.CharField(max_length=100)),
            ],
        ),
    ]
