# Generated by Django 3.2.12 on 2022-04-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlapApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnal',
            fields=[
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('F_Name', models.CharField(max_length=100)),
                ('L_Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Team_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlapApp.team')),
            ],
        ),
    ]
