# Generated by Django 3.2.12 on 2022-04-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SlapApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_stats',
            name='Shots',
        ),
    ]
