# Generated by Django 3.2.12 on 2022-04-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlapApp', '0002_personnal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnal',
            name='Team_ID',
            field=models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.team'),
        ),
    ]
