# Generated by Django 3.2.12 on 2022-04-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlapApp', '0002_remove_team_stats_shots'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_stats',
            name='Shots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
