# Generated by Django 3.2.12 on 2022-04-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlapApp', '0003_team_stats_shots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shot_ID', models.ForeignKey(db_column='Shot_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.shot')),
                ('Team_ID', models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.team')),
            ],
        ),
    ]
