# Generated by Django 3.2.12 on 2022-04-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlapApp', '0004_coach_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GamesPlayed', models.PositiveIntegerField()),
                ('Goals', models.PositiveIntegerField()),
                ('Assists', models.PositiveIntegerField()),
                ('Shots', models.PositiveIntegerField()),
                ('Hits', models.PositiveIntegerField()),
                ('F_wins', models.PositiveIntegerField()),
                ('F_losses', models.CharField(max_length=1)),
                ('Email', models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.personnal')),
                ('Team_ID', models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('Game_ID', models.AutoField(primary_key=True, serialize=False)),
                ('HomeAway', models.CharField(max_length=1)),
                ('Opponent', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Team_ID', models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.team')),
            ],
        ),
    ]
