# Generated by Django 3.2.12 on 2022-04-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlapApp', '0005_game_player_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('Shot_ID', models.AutoField(primary_key=True, serialize=False)),
                ('X_location', models.PositiveIntegerField()),
                ('Y_location', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wins', models.PositiveIntegerField()),
                ('Losses', models.PositiveIntegerField()),
                ('PIMS', models.PositiveIntegerField()),
                ('Shots_against', models.PositiveIntegerField()),
                ('Team_ID', models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.team')),
            ],
        ),
    ]
