# Generated by Django 3.2.12 on 2022-04-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlapApp', '0006_shot_team_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.personnal')),
                ('Game_ID', models.ForeignKey(db_column='Game_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.game')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_score', models.PositiveIntegerField()),
                ('Opponent_score', models.PositiveIntegerField()),
                ('Team_shots', models.PositiveIntegerField()),
                ('Opponent_shots', models.PositiveIntegerField()),
                ('Team_hits', models.PositiveIntegerField()),
                ('F_wins', models.PositiveIntegerField()),
                ('F_losses', models.PositiveIntegerField()),
                ('Game_ID', models.ForeignKey(db_column='Game_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.game')),
            ],
        ),
    ]
