# Generated by Django 3.2.12 on 2022-04-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlapApp', '0007_game_sheet_plays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.personnal')),
                ('Shot_ID', models.ForeignKey(db_column='Shot_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.shot')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_ID', models.ForeignKey(db_column='Game_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.game')),
                ('Shot_ID', models.ForeignKey(db_column='Shot_ID', on_delete=django.db.models.deletion.CASCADE, to='SlapApp.shot')),
            ],
        ),
    ]
