# Generated by Django 3.2.12 on 2022-04-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlapApp', '0008_game_logs_takes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Email', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
