# Generated by Django 3.2.12 on 2022-04-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlapApp', '0010_alter_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_stats',
            name='F_losses',
            field=models.PositiveIntegerField(),
        ),
    ]
