# Generated by Django 3.2.12 on 2022-04-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlapApp', '0011_alter_player_stats_f_losses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='id',
        ),
        migrations.RemoveField(
            model_name='game_sheet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.RemoveField(
            model_name='player_stats',
            name='id',
        ),
        migrations.RemoveField(
            model_name='team_stats',
            name='id',
        ),
        migrations.AlterField(
            model_name='coach',
            name='Email',
            field=models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SlapApp.personnal'),
        ),
        migrations.AlterField(
            model_name='game_sheet',
            name='Game_ID',
            field=models.ForeignKey(db_column='Game_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SlapApp.game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Email',
            field=models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SlapApp.personnal'),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='Email',
            field=models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SlapApp.personnal'),
        ),
        migrations.AlterField(
            model_name='team_stats',
            name='Team_ID',
            field=models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SlapApp.team'),
        ),
    ]
